AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Description: Name of this stack's enviornment
  StackName:
    Type: String
    Description: Base Name of this stack, this is usually used in prefixes for resources

Resources:
  # S3 bucket to store user files - such as profile pictures - and system files.
  FilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${StackName}-${Environment}-files"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
              - HEAD
              - PUT
              - POST
              - DELETE
            AllowedOrigins:
              - "*"
            ExposedHeaders:
              - authorization
              - x-amz-content-sha256
              - x-amz-date
              - x-amz-security-token
              - x-amz-user-agent
              - content-type
              - x-amz-acl
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
              - ETag
            AllowedHeaders:
              - "*"

Outputs:
  FilesBucketName:
    Value: !Ref FilesBucket
